name: Checkout
description: Checkout specific branch

inputs:
  path:
    default: '.'
    description: 'Clone path'
    required: false
  repo:
    description: 'Target repository'
    required: true
  ref:
    default: 'main'
    description: 'Target branch'
    required: false

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      ref: ${{ inputs.ref }}
      repository: ${{ inputs.repo }}
      path: ${{ inputs.path }}

  - name: List files
    shell: bash
    run: |
      ls -la
      ls -lR bundletool-action
