name: Checkout
description: Checkout specific branch

inputs:
  ref:
    description: 'Target branch'
    required: false

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      ref: ${{ inputs.ref }}
      repositry: tetsuuu/bundletool-action
      path: bundletool-action

  - name: List files
    shell: bash
    run: |
      ls -la
      ls -lR bundletool-action
