name: Checkout
description: Checkout specific branch

inputs:
  ref:
    description: 'Target branch'
    required: false

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v4
    with:
      ref: ${{ inputs.ref }}
