name: Use aqua installer for cli management

on:
  workflow_dispatch:
  # pull_request:
  #   types:
  #     - opened
  #     - reopened
  #     - synchronize
  #   branches:
  #     - develop

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Restore Cache Terraform Plugin Cache
        uses: actions/cache/restore@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.29.0
      - name: Check Aqua CLI
        run: |
          aqua --version
          conftest --version
          sops --version
          terraform --version
          tfmigrate --version
          yq --version
      - name: Restore and Save Cache Terraform Plugin Cache
        uses: actions/cache@v4
        with:
          path: ~/.local/share/aquaproj-aqua
          key: v1-aqua-installer-${{runner.os}}-${{runner.arch}}-${{hashFiles('aqua.yaml')}}
