name: Use aqua installer for cli management

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
    branches:
      - develop

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  setup:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: aquaproj/aqua-installer@v3.0.1
        with:
          aqua_version: v2.29.0
      - name: Check Aqua CLI
        run: |
          aqua --version
          terraform --version
          conftest --version
          tfmigrate --version
