name: Comment asobi
on:
  issue_comment:
    types: [created, edited]

jobs:
  asobi:
    if: ${{ github.event.issue.pull_request }}
    permissions:
      pull-requests: write
      deployments: write
      contents: write
      checks: read
    runs-on: ubuntu-22.04
    steps:
      - name: branch-deploy
        id: branch-build
        uses: github/branch-deploy@v7.5.1
        with:
          environment: "dev"
          environment_targets: "dev,stg,prd,dayo"
          production_environment: "prd"
          stable_branch: "develop"
          trigger: "/asobi"
          skip_ci: "true"

      - uses: actions/checkout@v4
        if: ${{ steps.branch-build.outputs.continue == 'true' }}
        with:
          ref: ${{ steps.branch-build.outputs.ref }}

      - name: Get argument
        id: get_arg
        run: |
          echo "ARGS=`echo ${{ github.event.comment.body }} | awk '{print $2}'`" >> "$GITHUB_OUTPUT"
          echo "ROOT_PWD=`pwd`" >> "$GITHUB_OUTPUT"

      - name: Arg trigger
        if: contains(github.event.comment.body, 'dayo')
        uses: ./.github/actions/asobi
        with:
          arg: ${{ steps.get_arg.outputs.ARGS }}
          root_pwd: ${{ steps.get_arg.outputs.ROOT_PWD }}

      - name: Refer
        run: |
          echo "branch_ref: ${{ github.ref }}"
