name: Comment asobi
on:
  issue_comment:
    types: [created, edited]

permissions:
  pull-requests: write
  deployments: write
  contents: write
  checks: read

jobs:
  jyunbi:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-22.04
    outputs:
      continue: ${{ steps.branch-build.outputs.continue }}
      ref: ${{ steps.branch-build.outputs.ref }}
      repositry: ${{ steps.duplicate.outputs.environment }}
      sha: ${{ steps.branch-build.outputs.sha }}
      service: ${{ steps.branch-build.outputs.environment }}
    steps:
      - name: branch-deploy
        id: branch-build
        uses: github/branch-deploy@v8.1.0
        with:
          deploy_message_path: ".github/asobi_message.md"
          environment: "toybox"
          environment_targets: "dev,prd,dayo,asobi,docker"
          production_environments: "prd"
          stable_branch: "develop"
          trigger: "/asobi"
          skip_ci: "true"

      - name: duplicate output key
        id: duplicate
        run: |
          echo "environment=local" >> "$GITHUB_OUTPUT"

  asobi:
    needs: jyunbi
    if: ${{ needs.jyunbi.outputs.continue }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.jyunbi.outputs.ref }}

      - name: Get argument
        id: get_arg
        run: |
          echo "ROOT_PWD=`pwd`" >> "$GITHUB_OUTPUT"

      - name: Arg trigger
        if: ${{ needs.jyunbi.outputs.service == 'dayo' }}
        uses: ./.github/actions/asobi
        with:
          arg: ${{ needs.jyunbi.outputs.service }}
          root_pwd: ${{ steps.get_arg.outputs.ROOT_PWD }}

      - name: Build Image
        if: ${{ needs.jyunbi.outputs.service != 'dayo' }}
        uses: ./.github/actions/build_image
        with:
          sha: ${{ needs.jyunbi.outputs.sha }}
          repositry: ${{ needs.jyunbi.outputs.repositry }}
          target: ${{ needs.jyunbi.outputs.service }}
