name: Comment asobi
on:
  issue_comment:
    types: [created, edited]

jobs:
  asobi:
    if: contains(github.event.comment.html_url, '/pull/') && startsWith(github.event.comment.body, '/asobi')
    permissions:
      pull-requests: write
      contents: write
      checks: read
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Get argument
        run: |
          echo "arg: ${{ github.event.comment.body }}"

      - name: Arg trigger
        if: contains(github.event.comment.body, 'dayo')
        uses: ./.github/actions/asobi
        with:
          arg: ${{ github.event.comment.body }}

      - name: Refer
        run: |
          echo "branch_ref: ${{ github.ref }}"
