name: git-pr-release
on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  gitPrRelease:
    name: git-pr-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - run: gem install --no-document git-pr-release

      - run: git-pr-release --no-fetch
        env:
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TZ: Asia/Tokyo
