name: git-pr-release
on:
  push:
    branches:
      - develop

jobs:
  gitPrRelease:
    name: git-pr-release
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - run: gem install --no-document git-pr-release

      - run: git-pr-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: main
          GIT_PR_RELEASE_BRANCH_STAGING: develop
          TZ: Asia/Tokyo
