name: Comment by comment body
on:
  issue_comment:
    types: [created, edited]

permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  comment:
    name: "Check Comment"
    if: >-
      contains(github.event.comment.html_url, '/pull/') &&
      contains(github.event.comment.body, 'hello') &&
      contains(github.event.comment.body, 'test')
    runs-on: ubuntu-latest
    steps:
    # - name: Checkout
    #   uses: actions/checkout@v4

    - uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'こんにちは！'
          })
